# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cephmgr < Formula
  desc ""
  homepage "https://github.com/vtarmo/cephmgr"
  version "0.1"

  on_macos do
    url "https://github.com/vtarmo/cephmgr/releases/download/v0.1/cephmgr_0.1_darwin_all.tar.gz"
    sha256 "a86c00fa100d8ad0cec1f4e3627a271d19a168471680086ede1bb17fa9f40bed"

    def install
      bin.install "cephmgr"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vtarmo/cephmgr/releases/download/v0.1/cephmgr_0.1_linux_arm64.tar.gz"
      sha256 "42b0bf481bf2d0c1c538411e4d04d191c439b94154e46205a80db642b80ddd1e"

      def install
        bin.install "cephmgr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vtarmo/cephmgr/releases/download/v0.1/cephmgr_0.1_linux_amd64.tar.gz"
      sha256 "54650795fb44b790be71fbdc60e552a72fd313209e87bc5d81f6a11e24512e85"

      def install
        bin.install "cephmgr"
      end
    end
  end
end
